export const CREATE_CALENDAR: string = 'CREATE_CALENDAR';
export const CREATE_CALENDAR_SUCCESS: string = 'CREATE_CALENDAR_SUCCESS';
export const CREATE_CALENDAR_ERROR: string = 'CREATE_CALENDAR_ERROR';

export const GET_CALENDAR: string = 'GET_CALENDAR';
export const GET_CALENDAR_SUCCESS: string = 'GET_CALENDAR_SUCCESS';
export const GET_CALENDAR_ERROR: string = 'GET_CALENDAR_ERROR';
