export const CREATE_CALENDAR = 'CREATE_CALENDAR';
export const CREATE_CALENDAR_SUCCESS = 'CREATE_CALENDAR_SUCCESS';
export const CREATE_CALENDAR_ERROR = 'CREATE_CALENDAR_ERROR';

export const GET_CALENDAR = 'GET_CALENDAR';
export const GET_CALENDAR_SUCCESS = 'GET_CALENDAR_SUCCESS';
export const GET_CALENDAR_ERROR = 'GET_CALENDAR_ERROR';