export const CREATE_EVENT = 'CREATE_EVENT';
export const CREATE_EVENT_SUCCESS = 'CREATE_EVENT_SUCCESS';
export const CREATE_EVENT_ERROR = 'CREATE_EVENT_ERROR';

export const MARK_AS_IMPORTANT = 'MARK_AS_IMPORTANT';
export const MARK_AS_IMPORTANT_SUCCESS = 'MARK_AS_IMPORTANT_SUCCESS';
export const MARK_AS_IMPORTANT_ERROR = 'MARK_AS_IMPORTANT_ERROR';
